server:
  port: 8080

spring:
  application:
    name: user
  elasticsearch:
    uris: http://localhost:9200

logging:
  config: classpath:logback/logback-spring.xml
  level:
#    tracer: TRACE
    com.es: DEBUG
#    org:
#      elasticsearch:
#        client: TRACE
